const assist = {
  meta: {
    title: "Wave Assist, Titan Wave Media Console",
    conversation: "Conversation, Wave Assist, Titan Wave Media Console",
  },
  title: "Wave Assist",
  lede: "Your chat assistant. Teach it about your business, test it, put it on your website, and read every conversation it has.",
  teamTitle: "Wave Assist for {business}",
  teamLede: "You can change anything here for them. Every change you make goes in the team log.",
  teamCrumb: "Assistants",

  switch: {
    label: "Answer customers on your websites",
    on: "On. The chat shows on the websites in your setup.",
    off: "Off. The chat doesn't show anywhere. You can still test it.",
    noSites: "Add a website in Setup, or the chat has nowhere to show.",
    noReach: "Add a WhatsApp number, a phone number or an email in Setup first, so customers can always reach a person.",
    turnedOn: "Wave Assist is on. It shows on your websites within a minute.",
    turnedOff: "Wave Assist is off. It goes from your websites within a minute.",
  },
  chips: { on: "On", off: "Off" },

  tabs: {
    label: "Wave Assist",
    setup: "Setup",
    test: "Test",
    install: "Install",
    conversations: "Conversations",
    questions: "Questions it couldn't answer",
  },

  stats: {
    label: "Wave Assist in numbers",
    conversations: "Conversations, last 30 days",
    conversationsSub: "Test chats aren't counted",
    answered: "Answered without help",
    answeredSub: "{answered} of {total} conversations",
    handed: "Handed over to you",
    handedSub: "On WhatsApp, or by leaving their details",
    busiest: "Busiest time",
    busiestValue: "{from} to {to}",
    busiestSub: "When most conversations start, Lagos time",
    month: "This month",
    monthValue: "{used} of {limit}",
    monthSub: "Conversations this month, against your monthly limit",
    monthOver: "{count} more came after the limit, and were offered a person",
    none: "None yet",
    noneSub: "Nothing to count yet",
  },

  setup: {
    title: "What your assistant knows",
    text: "It answers only from what you write here. Write it the way you'd explain it to someone new on your team.",
    business: "Your business",
    name: "Business name",
    nameHint: "Customers see it on the chat button: Chat with {business}.",
    sells: "What you sell",
    sellsHint: "Your products or services, in a few lines.",
    prices: "Prices or menu",
    pricesHint: "Paste your price list or menu. It only gives prices that are written here.",
    hours: "Opening hours",
    areas: "Where you deliver or work",
    reach: "How customers reach a person",
    reachText: "Add at least one of these. Your assistant can't be switched on without one, because customers must always be able to reach a person. When it isn't sure, or a customer asks for a person, it shows every way you add here.",
    whatsapp: "WhatsApp number",
    whatsappHint: "With the country code. We add Nigeria's 234 to a number that starts with 0.",
    phone: "Phone number",
    email: "Email",
    qa: "Questions and answers",
    qaText: "The questions your customers ask most, with your answers. Up to 50.",
    qaCount: "{count} of 50",
    question: "Question {n}",
    answer: "Answer {n}",
    removeQa: "Remove question {n}",
    addQa: "Add a question",
    qaFull: "That's 50, the most it can keep.",
    qaEmpty: "No questions yet. Add the ones your customers ask most.",
    extra: "Anything else it should know",
    extraHint: "Paste anything that helps: how to pay, how long delivery takes, your returns policy.",
    knowledge: "{count} of 50,000 characters used, across everything it knows.",
    docs: {
      title: "Documents",
      text: "Add a price list, a menu, a policy or a guide as a PDF, a Word file (.docx) or a plain text file (.txt). We take the text out, and you check it before it's added. Up to 5 documents, each up to 4 MB. We don't keep the file itself.",
      count: "{count} of 5",
      add: "Add a document",
      reading: "Reading {name}",
      rules: "PDF, Word (.docx) or plain text (.txt), up to 4 MB.",
      empty: "No documents yet.",
      chars: "{count} characters",
      edit: "Check the text",
      editLabel: "Check the text of {name}",
      remove: "Remove {name}",
      reviewTitle: "Check the text from {name}",
      reviewText: "This is the text we took out of your document. Change anything that's wrong, and take out anything your assistant shouldn't say to customers. Then add it.",
      nameLabel: "Name",
      textLabel: "The text",
      cut: "This document is longer than your assistant can keep, so only its first 50,000 characters are here.",
      addIt: "Add it",
      keep: "Keep these changes",
      cancel: "Cancel",
      added: "{name} was added. Save changes to keep it.",
      changed: "{name} was changed. Save changes to keep it.",
      removed: "{name} was removed. Save changes to keep it.",
      full: "That's 5 documents, the most it can keep. Remove one to add another.",
      errors: {
        type: "We can read PDF, Word (.docx) and plain text (.txt) files. Save it as one of those, or paste the text in Anything else it should know.",
        size: "That file is over 4 MB. Make it smaller, or paste its text in Anything else it should know.",
        scan: "This PDF has no text we can read. It may be a scan or a photo of a page. Please paste its text in Anything else it should know instead.",
        empty: "We couldn't find any text in that file. Please paste its text in Anything else it should know instead.",
        locked: "That file is locked with a password. Save a copy without the password, or paste its text instead.",
        read: "We couldn't read that file. Try saving it again as a PDF, Word or text file, or paste its text instead.",
        slow: "That file took too long to read. Try a smaller file, or paste its text instead.",
        limit: "You've added a lot of documents in the last hour. Please try again later.",
        text: "Add some text, or press Cancel.",
      },
    },
    chat: "The chat",
    greeting: "Greeting",
    greetingHint: "The first message customers see. Left empty, it says: {greeting}",
    starters: "Starter questions",
    startersHint: "Up to 4 questions customers can press instead of typing.",
    starter: "Starter question {n}",
    look: "The look",
    color: "Button colour",
    colorPick: "Pick a colour",
    colorCode: "Colour code",
    colorHint: "Pick a colour, or type its code with a # and 6 letters or numbers.",
    textOn: "Text on the button: {text}. Contrast {ratio} to 1.",
    white: "white",
    black: "black",
    adjusted: "Neither white nor black text was easy to read on that colour, so we made it a little {way} to reach 4.6 to 1. The button uses {color}.",
    darker: "darker",
    lighter: "lighter",
    corner: "Where the button sits",
    corners: { right: "Bottom right", left: "Bottom left" },
    preview: "How the button looks",
    previewNote: "A picture of the button on a white page. It doesn't open anything.",
    label: "Chat with {business}",
    labelNoName: "Chat with us",
    sites: "Your websites",
    sitesText: "The chat only shows on these websites, up to 20.",
    site: "Website address",
    siteHint: "Type the address of your website. We take out https:// and anything after the name. The name with www and without it count as one website. Real websites need https. localhost, for testing, works over http.",
    addSite: "Add",
    removeSite: "Remove {site}",
    sitesEmpty: "No websites yet.",
    siteAdded: "{site} was added. Save changes to keep it.",
    siteErrors: {
      empty: "Type a website address first.",
      not_host: "That isn't a website address. Type just its name, the part after https://.",
      ip: "Use your website's name, not a number address.",
      single: "That's missing its ending, like .com or .ng.",
      port: "The number after the colon must be from 1 to 65535.",
      too_many: "That's 20, the most it can keep.",
      already: "{site} is already on the list.",
    },
    save: "Save changes",
    saved: "Saved. Your changes show on your websites within a minute.",
    savedAt: "Saved at {time}. Your changes show on your websites within a minute.",
    errors: {
      summary: "Some things need fixing before this can be saved. They're marked below.",
      long: "That's too long. It can be up to {max} characters.",
      whatsapp: "Check the WhatsApp number. Use digits, with the country code.",
      phone: "Check the phone number. Use digits, spaces and a plus sign only.",
      email: "Check the email address.",
      half: "Add both the question and the answer, or remove this one.",
      qaLong: "That's too long. A question can be up to 300 characters, and an answer up to 2,000.",
      many: "That's more than it can keep.",
      startersLong: "A starter question can be up to 150 characters.",
      color: "That isn't a colour code. Use a # and 6 letters or numbers.",
      sites: "Check the websites list.",
      reach: "Your assistant is on, so keep at least one way for customers to reach a person, or switch it off first.",
      knowledge: "Everything it knows can be up to 50,000 characters, and this comes to {count}. Shorten something, or remove a document.",
      docEmpty: "Each document needs a name and some text.",
    },
  },

  test: {
    title: "Try your assistant",
    text: "This is the real chat, with your saved setup. Ask it what your customers ask. Save any changes in Setup first.",
    frameTitle: "Test chat with {business}",
    restart: "Start again",
    restarted: "The test chat started again.",
    notCounted: "Test chats aren't kept, and they don't count towards your conversations or your stats.",
    off: "Your assistant is off, so only you can see it here. Your customers can't.",
    noToken: "The test chat can't open right now. Please try again in a moment.",
  },

  install: {
    noSitesTitle: "Add your website first",
    noSitesText: "The chat only shows on the websites you list. Add yours in Setup, then come back here for the code.",
    noSitesLink: "Add your website",
    codeTitle: "Your code",
    codeText: "Add this one line to every page of your website, just before the end of the body. That's all it needs.",
    codeLabel: "The code for your website",
    copy: "Copy the code",
    copied: "Copied. Paste it into your website.",
    copyFailed: "The code is selected. Copy it with your keyboard.",
    sites: "It shows on: {sites}.",
    off: "Your assistant is off, so the chat won't show yet. Switch it on at the top of this page.",
    seen: "Last seen on {site}, {date}.",
    notSeen: "We haven't seen the chat on your website yet. This says when it first opens there.",
    stepsTitle: "Where to paste it",
    steps: [
      {
        name: "WordPress",
        text: "Your theme may have a place for footer code in its settings. If it doesn't, a plugin that adds code to every page's header and footer does the same job. Paste the line in the footer part, and save.",
      },
      {
        name: "Wix",
        text: "In your Wix dashboard, look in the settings for custom code. Add the line, choose all pages, and place it at the end of the body. Wix may ask for a paid plan with your own domain first.",
      },
      {
        name: "Shopify",
        text: "Open your theme's code editor, then the theme.liquid file. Paste the line just before </body>, and save.",
      },
      {
        name: "A plain website",
        text: "Paste the line just before </body> on every page. If your pages share one footer file, paste it there once.",
      },
    ],
    cspTitle: "If your website has a content security policy",
    csp: "Most websites don't set one. If yours does, add {site} to its script-src and frame-src, or the browser will block the chat.",
    send: "Send these steps to my web person",
    sendHelp: "Opens an email with the code and these steps, ready to send.",
    mail: {
      subject: "Please add our website chat: one line of code",
      intro: "Hello,\r\n\r\nPlease add our website chat, Wave Assist from Titan Wave Media, to our website. It needs this one line on every page, just before the end of the body:",
      sites: "It only shows on these websites: {sites}.",
      csp: "If our website sets its own content security policy, please add {site} to its script-src and frame-src.",
      thanks: "Thank you.",
    },
  },

  conversations: {
    waitingTitle: "Waiting for you",
    waitingText: "These customers left their details. Get back to them, then mark each one as handled.",
    name: "Name",
    phone: "Phone",
    email: "Email",
    question: "What they asked",
    notGiven: "Not given",
    left: "Left {date}",
    handled: "Mark as handled",
    handledDone: "Marked as handled.",
    open: "Open",
    openLabel: "Open the conversation from {date}",
    openWith: "Open the conversation with {name}",
    noConversation: "Left without a conversation, so there is nothing to open.",
    chartTitle: "Conversations a day",
    chartSub: "Last 14 days, Lagos time",
    chartDay: "{day}: {count}",
    searchLabel: "Search the messages",
    search: "Search",
    clear: "Clear the search",
    filtersLabel: "Show",
    filters: { all: "All", answered: "Answered", handed: "Handed over", unanswered: "Couldn't answer" },
    table: { when: "When", first: "First message", count: "Customer messages", result: "Result", open: "Open" },
    results: { answered: "Answered", handed_over: "Handed over", unanswered: "Couldn't answer" },
    overLimit: "After the monthly limit",
    noFirst: "No message",
    found: "{count} conversations",
    foundOne: "1 conversation",
    searching: "{count} conversations with \"{q}\"",
    searchingOne: "1 conversation with \"{q}\"",
    empty: "No conversations yet. They show here as soon as a customer writes in the chat on your website.",
    emptyFilter: "No conversations match.",
    page: "Page {page} of {pages}",
    newer: "Newer",
    older: "Older",
    pagesLabel: "Pages of conversations",
    kept: "Conversations are kept for 6 months, then deleted.",
  },

  conversation: {
    crumb: "Conversations",
    title: "Conversation",
    started: "Started {date}",
    customer: "Customer",
    assistant: "Wave Assist",
    couldnt: "It couldn't answer this",
    offered: "It offered a person",
    whatsapp: "The customer opened your WhatsApp on {date}.",
    overLimit: "This conversation started after your monthly limit was reached, so it only offered a person.",
    ended: "The customer pressed Start again, so this conversation is closed.",
    details: "Details the customer left",
    noDetails: "The customer didn't leave their details here.",
    handledOn: "Handled {date}",
    waiting: "Waiting",
    delete: "Delete this conversation",
    deleteTitle: "Delete this conversation?",
    deleteText: "It's deleted for good, with its messages and any details the customer left. This can't be undone.",
    deleteYes: "Delete it",
    deleteNo: "Keep it",
    deleted: "The conversation was deleted.",
    ownerOnly: "Only an owner of {business} can delete a conversation.",
    kept: "Conversations are kept for 6 months, then deleted.",
    missing: "This conversation isn't here. It may have been deleted.",
  },

  questions: {
    title: "Questions it couldn't answer",
    text: "What customers asked that your setup didn't answer. The same question asked more than once shows once. Add an answer, and it uses it from then on.",
    asked: "Asked {count} times",
    askedOnce: "Asked once",
    last: "last on {date}",
    add: "Add an answer",
    addLabel: "Add an answer to: {question}",
    dialogTitle: "Add an answer",
    question: "Question",
    questionHint: "Change the words if you like. Customers don't need to ask it exactly this way.",
    answer: "Your answer",
    save: "Add the answer",
    cancel: "Cancel",
    added: "Added. It uses this answer from now on, and on your websites within a minute.",
    full: "You already have 50 questions and answers, the most it can keep. Remove one in Setup, then try again.",
    errors: {
      question: "Write the question.",
      answer: "Write the answer.",
      long: "That's too long. A question can be up to 300 characters, and an answer up to 2,000.",
    },
    empty: "Nothing here. When it can't answer a question, the question shows here.",
    more: "These are the {count} questions asked most.",
  },

  team: {
    limit: "Monthly limit",
    limitHint: "Conversations a Lagos calendar month. After that, new conversations only offer a person.",
    limitSave: "Save the limit",
    limitSaved: "The monthly limit is now {limit}.",
    limitError: "Use a whole number from 0 to 1,000,000.",
    planTitle: "Plan and billing",
    planText: "The monthly price and the conversations it covers. A new price applies from the next invoice. Nothing is charged while the price is empty.",
    price: "Monthly price in naira",
    priceHint: "Leave it empty for no price yet. From ₦100.",
    priceError: "Use a price from ₦100 to ₦1,000,000,000, or leave it empty.",
    priceNeeded: "Billing is on, so keep a price, or switch billing off first.",
    planSave: "Save the plan",
    planSaved: "The plan is saved: {price} a month, up to {limit} conversations.",
    planSavedNoPrice: "The plan is saved with no price, up to {limit} conversations a month.",
    billing: "Send a Wave Assist invoice every month",
    billingOn: "On. The next invoice is on {date}, for {price}. It goes out with the daily run at 8 am, Lagos time.",
    billingOff: "Off. No Wave Assist invoices are sent.",
    billingNoPrice: "Set a price first.",
    billingNote: "Switching billing off stops new invoices. It doesn't cancel invoices already sent.",
    billingTurnedOn: "Billing is on. The first invoice goes out on {date}.",
    billingTurnedOff: "Billing is off. No new Wave Assist invoices will be sent.",
  },

  plan: {
    title: "Your plan",
    priceLabel: "Price",
    limitLabel: "Conversations",
    price: "{price} a month",
    noPrice: "No price yet",
    limit: "Up to {limit} conversations a month",
    next: "Next invoice: {date}",
    notBilled: "We haven't started monthly invoices for Wave Assist yet.",
    change: "Your plan is set by our team. To change it, talk to us.",
    talk: "Talk to us",
    talkHref: "/contact?need=tool&product=wave-assist",
  },

  failed: "That didn't go through. Please try again in a moment.",
  notFound: "That isn't here any more. It may have been deleted.",
};

export default assist;
