// Settings: Profile, Security, Notifications, Team and Your data.

const settings = {
  meta: { title: "Settings, Titan Wave Media Console" },
  title: "Settings",
  lede: "Your details, your security, who gets in, and your data.",
  tabs: { profile: "Profile", security: "Security", notifications: "Notifications", team: "Team", data: "Your data" },
  saved: "Saved.",
  failed: "That didn't go through. Please try again in a moment.",

  profile: {
    you: "Your details",
    name: "Your name",
    email: "Email",
    emailHelp: "Sign in links and receipts go here. To change it, ask us in Help.",
    save: "Save",
    business: "Business details",
    businessHelp: "These show on your invoices.",
    businessName: "Business name",
    phone: "Business phone",
    address: "Business address",
    ownerOnly: "Only the owner of {business} can change these.",
    errors: { name: "Enter your name.", business: "Enter your business name." },
  },

  security: {
    twostep: {
      title: "Two step sign in",
      label: "Ask for a code after the sign in link",
      help: "From an authenticator app on your phone, like Google Authenticator or Microsoft Authenticator.",
      on: "On. After the sign in link, we ask for the code from your phone.",
      off: "Off. Anyone who can open your email can sign in.",
      setupTitle: "Turn on two step sign in",
      step1: "Open your authenticator app and scan this code. Or type the key below the code.",
      key: "Key",
      qrAlt: "QR code for your authenticator app",
      step2: "Type the 6 digit code your app shows for Titan Wave Media.",
      confirm: "Turn it on",
      codesTitle: "Your backup codes",
      codesText: "Keep these somewhere safe, like a password manager. Each one works once, if you lose your phone. This is the only time we show them.",
      codesWarn: "Using a backup code turns off two step sign in, so you can set it up again.",
      copy: "Copy the codes",
      copied: "Copied.",
      done: "I've kept them safe",
      newCodes: "Get new backup codes",
      newCodesText: "Your old backup codes will stop working.",
      turnOff: "Turn it off",
      offTitle: "Turn off two step sign in?",
      offText: "Anyone who can open your email will be able to sign in.",
      offButton: "Turn it off",
      cancel: "Keep it on",
      cancelNew: "Cancel",
      codeLength: "Type all 6 digits.",
      turnedOn: "Two step sign in is on.",
      turnedOff: "Two step sign in is off.",
    },
    devices: {
      title: "Sign out of all devices",
      text: "Signs you out everywhere, including here. Use it if you lost a phone or signed in on a computer that isn't yours.",
      button: "Sign out of all devices",
    },
    history: {
      title: "Recent sign ins",
      help: "Your last 20 sign ins.",
      when: "When",
      how: "How",
      device: "Browser and device",
      empty: "No sign ins yet.",
      methods: {
        link: "Sign in link",
        link_code: "Sign in link and code",
        link_backup: "Sign in link and backup code",
        google: "Google",
        google_code: "Google and code",
        google_backup: "Google and backup code",
      },
      unknown: "Not known",
    },
  },

  notifications: {
    title: "Tell me by email when",
    items: {
      notify_projects: { label: "There's news on a project", help: "A reply in the chat, a new file or a new step" },
      notify_billing: { label: "An invoice or a receipt is ready", help: "New invoices, reminders and receipts" },
      notify_news: { label: "A product opens", help: "At most once a month" },
    },
    note: "Sign in links and messages about your account always come by email.",
  },

  team: {
    title: "Your team",
    text: "Invite the people who help you run the business. They sign in with their own email.",
    email: "Email",
    emailPlaceholder: "colleague@business.com",
    role: "Access",
    roles: { owner: "Owner", member: "Member" },
    roleHelp: "Owners can pay, invite and remove people, and delete the account. Members can see projects, chat and invoices.",
    invite: "Invite",
    you: "You",
    waiting: "Invited, waiting for them to sign in",
    remove: "Remove",
    removeTitle: "Remove {email}?",
    removeText: "They won't be able to open {business} in the console any more.",
    removeButton: "Remove",
    cancel: "Cancel",
    ownerOnly: "Only an owner can invite or remove people.",
    invited: "Invite sent to {email}.",
    removed: "{email} was removed.",
    errors: {
      email: "Enter an email like name@business.com.",
      already: "{email} is already on your team.",
      elsewhere: "{email} already has a Titan Wave Media account with another business.",
      self: "That's your own email.",
      lastOwner: "Your business needs at least one owner.",
    },
  },

  data: {
    download: "Download your data",
    downloadText: "Everything we hold about you and your business, in one file: your details, projects, messages, invoices, receipts and sign ins.",
    downloadButton: "Download my data",
    delete: "Delete your account",
    deleteText: "We delete your business, your team, projects, files and messages. Invoices and receipts are kept, because tax law says we must.",
    deleteButton: "Delete my account",
    ownerOnly: "Only an owner of {business} can delete the account.",
    unpaid: "You have an invoice to pay. Pay it first, or ask us in Help, then you can delete your account.",
    confirmTitle: "Delete your account?",
    confirmText: "We delete {business} and everything in it. You can't undo this.",
    confirmLabel: "Type {business} to confirm",
    confirmWrong: "That doesn't match your business name.",
    confirmButton: "Delete my account",
    keep: "Keep it",
    deleted: "Your account is deleted.",
  },
};

export default settings;
