const teamLog = {
  meta: { title: "Log, Titan Wave Media Console" },
  title: "Log",
  lede: "What the team did: invoices sent, refunds, steps changed, members added and Wave Assist changes. Newest first.",
  when: "When",
  who: "Who",
  what: "What",
  empty: "Nothing yet.",
  actions: {
    invoice_sent: "Sent invoice {target}",
    reminder_sent: "Sent a reminder for {target}",
    refund_approved: "Approved a refund on {target}",
    refund_declined: "Declined a refund on {target}",
    step_changed: "Moved {target} to step {n}, {step}",
    quote_sent: "Sent a quote for {target}",
    client_invited: "Invited the client {target}",
    member_added: "Added {target} to the team",
    member_removed: "Removed {target} from the team",
    assist_setup: "Changed the Wave Assist setup of {target}",
    assist_on: "Switched on Wave Assist for {target}",
    assist_off: "Switched off Wave Assist for {target}",
    assist_limit: "Set the Wave Assist limit of {target} to {limit} conversations a month",
    assist_plan: "Set the Wave Assist plan of {target} to {price} a month for {limit} conversations",
    assist_plan_cleared: "Took the Wave Assist price off {target}, with {limit} conversations a month",
    assist_billing_on: "Switched on Wave Assist billing for {target}",
    assist_billing_off: "Switched off Wave Assist billing for {target}",
    assist_handled: "Marked a Wave Assist handover for {target} as handled",
    assist_deleted: "Deleted a Wave Assist conversation of {target}",
    assist_answer: "Added an answer to the Wave Assist of {target}: {question}",
  },
};

export default teamLog;
